// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using catalog.api.Services.CatalogDbContext;

namespace catalog.api.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("catalog.api.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WheelSize")
                        .HasColumnType("int");

                    b.Property<int>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "f920e320-98c8-4b44-bcb1-f12de882aab4",
                            Brand = "Raleigh",
                            Color = "Black",
                            Model = "Mongoose",
                            Price = 1799.99m,
                            Style = "BMX",
                            WheelSize = 17,
                            Wheels = 2
                        },
                        new
                        {
                            Id = "69f0858b-718e-410b-9c9c-86e02cf407d9",
                            Brand = "Raleigh",
                            Color = "Red",
                            Model = "Panther",
                            Price = 2499.99m,
                            Style = "RACING",
                            WheelSize = 22,
                            Wheels = 2
                        },
                        new
                        {
                            Id = "24b6a7de-9a97-4f8f-a2ad-a58c73ffd229",
                            Brand = "Armstrong",
                            Color = "Silver",
                            Model = "Mongoose",
                            Price = 2999.99m,
                            Style = "RACING",
                            WheelSize = 22,
                            Wheels = 2
                        },
                        new
                        {
                            Id = "2ace51d8-ca56-41ff-a74a-93c750092079",
                            Brand = "Peagot",
                            Color = "Silver-Gray",
                            Model = "Sprinter-X2",
                            Price = 1299.99m,
                            Style = "BMX",
                            WheelSize = 17,
                            Wheels = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
